# IP versions supported: 'on' or 'off', default 'off'
IP_VERSIONS:
  v4: on
  v6: on

SET_NAMES:
  whitelist: whitelist
  blacklist: blacklist
  abuselist: abuselist
  country: country

# Default chain policy
DEFAULT_POLICY: accept

# Block policy: 'drop' or 'reject', default: 'drop'
BLOCK_POLICY: drop

# Logging configuration
# enable: Turn logging on or off (true/false)
# rate: Packet rate limit (packets/minute)
# burst: Packet burst limit
LOGGING:
  enabled: true
  rate: 10
  burst: 5

# Input interface name. If this is commented out, the default gateway interface will be used
# IIFNAME: eth0

# ASN URL templates - use {asn} as placeholder for the ASN number
ASN_URLS:
  v4: "https://raw.githubusercontent.com/ipverse/asn-ip/master/as/{asn}/ipv4-aggregated.txt"
  v6: "https://raw.githubusercontent.com/ipverse/asn-ip/master/as/{asn}/ipv6-aggregated.txt"

# Whitelist: IP or Network adresses
WHITELIST:
  v4:
    - 127.0.0.1
    - 10.0.0.0/8
    - 169.254.0.0/16
    - 192.168.0.0/16
    - 100.64.0.0/10
  v6:
    - fc00::/7
    - fd00::/8
    - fe80::/10

BLACKLIST:
  v4:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
  v6:

# URLs to direct IP or CIDR notation or AS<digits>
# For example, with: https://iplists.firehol.org/
ABUSELIST:
  v4:
    - AS37963 #ALIBABA-CN-NET
    - AS45102 #ALIBABA-CN-NET
    - https://iplists.firehol.org/files/bi_any_0_1d.ipset
    - https://iplists.firehol.org/files/haley_ssh.ipset
    - https://iplists.firehol.org/files/firehol_level2.netset
  v6:
    - AS37963 #ALIBABA-CN-NET
    - AS45102 #ALIBABA-CN-NET

# Country list: two letter country codes defined in ISO 3166-1
# https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
COUNTRY_LIST:
  - cn 
