## IP versions supported with allowed minimum CIDR prefix
## Defaults: v4: 8, v6: 16
# NET:
#   v4:
#     enabled: yes 
#     min_prefix: 8
#   v6:
#     enabled: yes
#     min_prefix: 16

## Default chain policy
# DEFAULT_POLICY: accept

## Block policy: 'drop' or 'reject', default: 'drop'
# BLOCK_POLICY: drop

## Input interface name. If this is commented out, the default gateway interface will be used
# IIFNAME: eth0

## Set names as they appear in the template without ip version suffix
# SET_NAMES:
#   whitelist: whitelist
#   blacklist: blacklist
#   abuselist: abuselist
#   country: country

## Logging configuration
## enable: Logging state 
## rate: Packet rate limit (packets/minute)
## burst: Packet burst limit
# LOGGING:
#   enabled: yes
#   ratelimiting: yes
#   rate: 10
#   burst: 5

## ASN and country IP sources, `null` means don't process, no key/commented means default url
# SOURCES:
#   asn:                                                                                                                                                                              
#     v4: "https://raw.githubusercontent.com/ipverse/asn-ip/master/as/{asn}/ipv4-aggregated.txt"                                                                                      
#     v6: "https://raw.githubusercontent.com/ipverse/asn-ip/master/as/{asn}/ipv6-aggregated.txt"                                                                                      
#   country:                                                                                                                                                                          
#     v4: "https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/master/ipv4/{country}.cidr"                                                                               
#      # - "https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/geolite2_country/country_{country}.netset"                                                    
#      # - "https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/ip2location_country/ip2location_country_{country}.netset"                                     
#      # - "https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/ipdeny_country/id_country_{country}.netset"                                                   
#      # - "https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/ipip_country/ipip_country_{country}.netset"                                                   
#     v6: "https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/master/ipv6/{country}.cidr" 

## Static list: IP or Network adresses
WHITELIST:
  v4:
    - 127.0.0.1
    - 10.0.0.0/8
    - 169.254.0.0/16
    - 192.168.0.0/16
    - 100.64.0.0/10
  v6:
    - fc00::/7
    - fd00::/8
    - fe80::/10

## Static list: IP or Network adresses
BLACKLIST:
  v4:
    - 224.0.0.0/3 # Multicast

## Dynamic list: ASNs, local and remote source support
ABUSELIST:
  v4:
    # Remote lists with https:// scheme
    - https://iplists.firehol.org/files/firehol_level1.netset
    # - https://iplists.firehol.org/files/firehol_level2.netset
    # - https://iplists.firehol.org/files/firehol_abusers_1d.netset
    # - https://iplists.firehol.org/files/firehol_abusers_30d.netset
    # - https://iplists.firehol.org/files/bi_any_0_1d.ipset
    # - https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/openai/ipv4_merged.txt  # OpenAI
    # - https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/perplexity/ipv4_merged.txt # Perplexity
    # ...with min_prefix override
    - url: https://iplists.firehol.org/files/firehol_level2.netset
      min_prefix: 24
      # Local files with file:// scheme
    - url: file://test/ipv4-test.netset
      min_prefix: 0
    # ASN resolution
    - AS37963 # ALIBABA
    - AS45102 # ALIBABA
  v6:
    - AS37963 # ALIBABA
    - AS45102 # ALIBABA

## Country list: two letter country codes defined in ISO 3166-1
## https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
COUNTRY_LIST:
  - cn 
